name: Android Build and Test

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'

      - name: Get packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Run tests
        run: flutter test
