name: iOS Build and Test

on:
  push:
    branches:
      - development

jobs:

  build:
    runs-on: macos-latest
    steps:
      - run: flutter channel master
      - run: flutter upgrade
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos
