name: Windows Build and Test

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'

      - name: Get packages
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows

      - name: Run tests
        run: flutter test
